settings: 
  authSecret: "cbgCqUIVKfZook1AFiFZvFJVbOAYNKD4"

database: 
  name: "DbBuildUp"
  connectionString: "mongodb://localhost:27017"
  collections: 
    users: "users"
    builders: "builders"
    coachs: "coachs"
    projects: "projects"
    buildOns: "buildOns"
    buildOnSteps: "buildOnSteps"