// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Coach struct {
	CandidatingDate time.Time `json:"candidatingDate"`
	Situation       string    `json:"situation"`
	Description     string    `json:"description"`
	Builders        []*User   `json:"builders"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewBuilder struct {
	Situation   string `json:"situation"`
	Description string `json:"description"`
}

type NewCoach struct {
	Situation   string `json:"situation"`
	Description string `json:"description"`
}

type NewUser struct {
	Email     string      `json:"email"`
	Password  string      `json:"password"`
	FirstName string      `json:"firstName"`
	LastName  string      `json:"lastName"`
	Builder   *NewBuilder `json:"builder"`
	Coach     *NewCoach   `json:"coach"`
}

type Project struct {
	ID string `json:"id"`
}
